name: RageLandsCUSTOM
version: 2.1
main: com.potato.ragelandscustom.Main
author: "Licensed (Potato_dodo0)"
api-version: '1.20'
description: "A Custom ragelands plugin made by Licensed"
load: POSTWORLD
depend:
  - Factions
  - Vault
  - packetevents
commands:
  giveitem:
    usage: "Usage : /giveitem <item> <player>"
    aliases: gt
    permission: ragelands.admin
    default: op
  ejectpassengers:
    usage: "Usage : /ejectpassengers || /ejps"
    aliases: ejps
  reloadragelandsplugin:
      permission : ragelands.reload
      description: "Allows players to reload the plugin."
      default: op
      aliases: rrp
      usage: "Usage : /reloadragelandsplugin"
  ironman:
    aliases:
      - im
  suits:
    aliases:
      - suit
  mk42:
  cooldownreset:
    aliases: cdres
    permission: ragelands.cooldownsreset

