name: RageLandsCUSTOM
version: 2.1
main: com.potato.rlcustomitems.Main
api-version: '1.20'
description:
depend:
  - Factions
  - Vault
commands:
  giveitem:
    usage: "Usage : /giveitem <item> <player>"
    aliases: gt
    permission: ragelands.admin
    default: op
  ejectpassengers:
    usage: "Usage : /ejectpassengers || /ejps"
    aliases: ejps
  reloadragelandsplugin:
      permission : ragelands.reload
      description: "Allows players to reload the plugin."
      default: op
      aliases: rrp
      usage: "Usage : /reloadragelandsplugin"
  ironman:
    aliases:
      - im
  suits:
    aliases:
      - suit
  mk42:

