#Enter your  vvvv license key here
licensekey: "INSERT YOUR LICENSE KEY HERE"
StingerRadius: 1600.0
LaserRadius: 144.0
TrackerRadius: 68
Mark50Protection: 3
Mark34Protection: 5
# Default stock volatility rate
stock_volatility:
  default: 0.05  # Default volatility rate (5% by default)

# Configuration for individual stocks
stocks:
  rln:
    price: 23500.0    # Initial price of RLN stock
    volatility: 0.05  # Initial volatility rate for RLN stock
  peescoin:
    price: 0.002      # Initial price of PeesCoin
    volatility: 0.10  # Initial volatility rate for PeesCoin
  potatocoin:
    price: 0.05       # Initial price of PotatoCoin
    volatility: 0.20  # Initial volatility rate for PotatoCoin

# Stocks GUI settings
#00 01 02 03 04 05 06 07 08
#09 10 11 12 13 14 15 16 17
#18 19 10 11 12 13 14 15 16
gui:
  stock_market:
    title: "Stock Market"
    size: 27
    slots:
      rln: 11         # Slot for RLN stock in the GUI
      peescoin: 13    # Slot for PeesCoin in the GUI
      potatocoin: 15  # Slot for PotatoCoin in the GUI
